### ISSUE TITLE
Accessibility: Checklist

### ISSUE THREAD

**Issue by ktquez** [vue-a11y/vue-a11y.com#6]
Issue that gathers information to build the checklist page

**Comment by georgialoper** [comment]
I'm not sure how vue-specific we want this to be, but I think [vox media's checklist](http://accessibility.voxmedia.com/#engineers) provides an excellent jumping of point.

Their engineer checklist includes:

- [ ]  Use the correct HTML element for your content
- [ ]  Support keyboard navigation
- [ ]  Understand and use HTML landmarks
- [ ]  Write good alt text for your images
- [ ]  Design focus states to help users navigate and understand where they are
- [ ]  Help users understand inputs, and help them avoid and correct mistakes
- [ ]  Use ARIA attributes when applicable
- [ ]  Make links descriptive
- [ ]  Avoid images and iconography in pseudo-elements
- [ ]  Make SVGs accessible to assistive technology
- [ ]  Hide decorative elements from screen readers
- [ ]  Create alternate routes for users to access information
- [ ]  Links should be visually identifiable and have clear :focus and :active states

**Comment by ktquez** [comment]
Perfect @georgialoper 

We can try to list specific items to solve accessibility flaws that are common when developing JavaScript applications (focused on Vue.js) and merge with important items from other more comprehensive checklists.

Would you like to build this with us?

**Comment by georgialoper** [comment]
@ktquez I'm interested in contributing where I can.

I'm having trouble running the project locally. I'm getting `error @vuepress/plugin-blog apply ready failed. RangeError: Invalid array length at getIntervallers` when running `npm run dev`, do I need any keys to get started?

**Comment by ktquez** [comment]
@georgialoper Awesome, we are happy with your initiative.

I think it is a bug in the plugin, I will do a test and see if any version is causing this and give you feedback.

**Comment by ktquez** [comment]
@georgialoper 

I updated the README and the .env.example
Before running `npm run dev` you make `cp .env.example .env`.
